### ISSUE TITLE
Running against ansible 2.0.0.2-1 fails with complex variable error

### ISSUE THREAD

**Issue by ryanwalls** [marklee77/ansible-role-docker#4]
Error output:

```
ERROR! Complex args containing variables cannot use bare variables, and must use the full variable style ('{{var_name}}')
```

**Comment by marklee77** [comment]
Interesting. I haven't moved to ansible 2 yet. Can you get a more verbose error message? It would be good to pinpoint exactly which statement is causing the problem.

**Comment by ryanwalls** [comment]
I tried adding `-vvvv` and it didn't give me any more info.  Do you know of another flag to get more output?

**Comment by marklee77** [comment]
I'll try installing ansible2 later this week.

**Comment by ryanwalls** [comment]
Feel free to use my ansible docker image.  Makes it easy to try out new versions without installing.  https://hub.docker.com/r/ryanwalls/ansible-aws

**Comment by jccomputing** [comment]
I investigated the problem and the message we get is related to how the args variable is accessed in  `tasks/main.yml`.

Here is an example:
```
-  args: docker_package_info.args
+  args: "{{ docker_package_info.args }}"
```

After you fix that, you hit a more serious bug:
```
TASK [marklee77.docker : ensure docker requirements packages are installed] ****
task path: /home/jcc/src/test/roles/marklee77.docker/tasks/main.yml:31
fatal: [server1.local]: FAILED! => {"failed": true, "msg": "ERROR! ERROR! 'item' is undefined"}
```

I think that the problem is related to an [Ansible 2 issue](ansible/ansible#14181) I opened. You use the 'item' variable before it's defined, for example here in `vars/debian.yml`:
```
docker_package_info:
  pkg_mgr: apt
  args:
    pkg: "{{ item }}"
```

**Comment by marklee77** [comment]
Well, the first bug is easy enough to fix, though I think that switching to the second notation will actually generate a warning in ansible 1. The second bug might be harder to fix since I'm not sure how to tell ansible that "item" should only be evaluated once you're inside a loop.

I don't suppose ansible 2 has any backwards compatibility support via explicit playbook language versioning?

Your link to the Ansible 2 issue seems to be broken.

**Comment by juanluisbaptiste** [comment]
Any updates on this ? I'm seeing this on ubuntu 16.04.

**Comment by juanluisbaptiste** [comment]
PR fixing this among other things, like CentOS 7 support. https://github.com/marklee77/ansible-role-docker/pull/5

**Comment by marklee77** [comment]
Thanks @juanluisbaptiste !

**Comment by juanluisbaptiste** [comment]
No problem !
